MusicCloud.Webapp/Pages/Albums/Details.cshtml.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;
using System;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;

namespace MusicCloud.Webapp.Pages.Albums
{
  
    public class AlbumDetailsModel : PageModel
    {
        private readonly AlbumRepository _albums;
        private readonly SongRepository _songs;
        private readonly IMapper _mapper;
        private readonly AuthService _authService;
        public AlbumDetailsModel(AlbumRepository albums, SongRepository songs, IMapper mapper, AuthService authService)
        {
            _albums = albums;
            _songs = songs;
            _mapper = mapper;
            _authService = authService;
        }

        [FromRoute]
        public Guid Guid { get; set; }
        public Album Album { get; private set; } = default!;
        [BindProperty]
        public Dictionary<Guid, SongDto> EditSongs { get; set; } = new();

        public IActionResult OnPostEditSong(Guid guid, Guid songGuid, Dictionary<Guid, SongDto> editSongs)
        {
            if (!ModelState.IsValid) { return Page(); }
            var song = _songs.FindByGuid(songGuid);
            if (song is null) { return RedirectToPage(); }

            _mapper.Map(editSongs[songGuid], song);
            var (success, message) = _songs.Update(song);
            if (!success)
            {
                ModelState.AddModelError("", message);
                return Page();
            }
            return RedirectToPage();
        }
        public IActionResult OnGet(Guid guid)
        {
            return Page();
        }

        public override void OnPageHandlerExecuting(PageHandlerExecutingContext context)
        {
            var album = _albums.Set
                .Include(a => a.Songs)
                .ThenInclude(s => s.Genre)
                .Include(a => a.Artist)
                .ThenInclude(ar => ar.Manager)
                .FirstOrDefault(a => a.Guid == Guid);
            if (album is null)
            {
                context.Result = RedirectToPage("/Artists/Index");
                return;
            }
            Album = album;
            EditSongs =
                _songs.Set.Where(s => s.Album.Guid == Guid)
                .ProjectTo<SongDto>(_mapper.ConfigurationProvider)
                .ToDictionary(s => s.Guid, s => s);
        }

        public bool CanEditAlbum(Guid albumGuid) =>
        _authService.IsAdmin ||
            _albums.Set
            .FirstOrDefault(a => a.Guid == albumGuid)?
            .Artist?.Manager?.Username == _authService.Username;
    }
}

MusicCloud.Webapp/Pages/Albums/Edit.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;

namespace MusicCloud.Webapp.Pages.Albums
{
    [Authorize]
    public class EditAlbumModel : PageModel
    {
        private readonly AlbumRepository _albums;
        private readonly ArtistRepository _artists;
        private readonly IMapper _mapper;
        private readonly AuthService _authService;
        public EditAlbumModel(AlbumRepository albums, ArtistRepository artists, IMapper mapper, AuthService authService)
        {
            _albums = albums;
            _artists = artists;
            _mapper = mapper;
            _authService = authService;
        }
        [BindProperty]
        public AlbumDto Album { get; set; } = null!;
        [TempData]
        public string? Message { get; set; }
        public IEnumerable<SelectListItem> ArtistSelectList =>
            _artists.Set.OrderBy(ar => ar.ArtistName).Select(ar => new SelectListItem(ar.ArtistName, ar.Guid.ToString()));
        public IActionResult OnPost(Guid guid)
        {
            if (!ModelState.IsValid) { return Page(); }
            var album = _albums.Set
                .Include(a => a.Artist)
                .Include(a => a.Songs)
                .FirstOrDefault(a => a.Guid == guid);
            if (album is null) {
                Message = "The album doesn't exist.";
                return RedirectToPage("/Artists/Index");
            }
            
            var artist = _artists.FindByGuid(Album.ArtistGuid);
            if (artist is null) {
                Message = "The artist doesn't exist.";
                return RedirectToPage("/Artists/Index");
            }
            album.Artist = artist;

            album.Songs.ToList().ForEach(a => a.Artist = artist);
            _mapper.Map(Album, album);
            var (success, message) = _albums.Update(album);
            if(!success) { ModelState.AddModelError("", message); }
            return RedirectToPage("/Artists/Index");
        }
        public IActionResult OnGet(Guid guid)
        {
            var albums = _albums.Set
                .Include(a => a.Artist)
                .ThenInclude(ar => ar.Manager)
                .FirstOrDefault(a => a.Guid == guid);
            if (albums is null) { return RedirectToPage("/Artists/Index"); }
            if(!_authService.IsAdmin && _authService.Username != albums.Artist.Manager.Username)
            {
                return new ForbidResult();
            }
            Album = _mapper.Map<AlbumDto>(albums);
            return Page();
        }

        public bool CanEditArtist()
        {
            return _authService.IsAdmin;
        }
    }

}

MusicCloud.Webapp/Pages/Artists/Delete.cshtml.cs
using Castle.DynamicProxy.Generators.Emitters.SimpleAST;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Services;

namespace MusicCloud.Webapp.Pages.Artists
{
    [Authorize]
    public class DeleteArtistsModel : PageModel
    {
        private readonly ArtistRepository _artists;
        private readonly AuthService _authService;
        public DeleteArtistsModel(ArtistRepository artists, AuthService authService)
        {
            _artists = artists;
            _authService = authService;
        }
        [TempData]
        public string? Message { get; set; }
        public Artist Artist { get; set; } = default!;
        public IActionResult OnPostCancel() { return RedirectToPage("/Artists/Index"); }
        public IActionResult OnPostDelete(Guid guid)
        {
            var artist = _artists.FindByGuid(guid);
            if (artist == null) { return RedirectToPage("/Artists/Index"); }
            var (success, message) = _artists.Delete(artist);
            if (!success) { Message = message; }
            return RedirectToPage("/Artists/Index");
        }
        public IActionResult OnGet(Guid guid)
        {
            var artist = _artists.Set
                .Include(ar => ar.Manager)
                .FirstOrDefault(ar => ar.Guid == guid);
            if (artist == null) { return RedirectToPage("/Artists/Index"); }
            Artist = artist;
            if(!_authService.IsAdmin && _authService.Username != artist.Manager.Username) { return new ForbidResult(); }
            return Page();
        }
    }
}

MusicCloud.Webapp/Pages/Artists/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;
using System;
using System.Linq;

namespace MusicCloud.Webapp.Pages.Artists
{
    public class ArtistDetailsModel : PageModel
    {
        private readonly ArtistRepository _artists;
        private readonly AlbumRepository _albums;
        private readonly AuthService _authService;
        public ArtistDetailsModel(ArtistRepository artists, AlbumRepository albums, AuthService authService)
        {
            _artists = artists;
            _albums = albums;
            _authService = authService;
        }
        [BindProperty]
        public Artist Artist { get; set; } = default!;
        public IActionResult OnGet(Guid guid)
        {
            var artist = _artists.Set
                .Include(ar => ar.Albums)
                .Include(ar => ar.Songs)
                .Include(ar => ar.Manager)
                .FirstOrDefault(a => a.Guid == guid);

            if (artist == null)
            {
                return RedirectToPage("/Artists/Index");
            }
            Artist = artist;
            return Page();
        }
        public bool CanEditAlbum(Guid albumGuid) =>
        _authService.IsAdmin ||
            _albums.Set.FirstOrDefault(a => a.Guid == albumGuid)?.Artist.Manager?.Username == _authService.Username;
    }
}

MusicCloud.Webapp/Pages/Artists/Edit.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;

namespace MusicCloud.Webapp.Pages.Artists
{
    [Authorize]
    public class EditArtistModel : PageModel
    {
        private readonly ArtistRepository _artists;
        private readonly IMapper _mapper;
        private readonly AuthService _authService;
        public EditArtistModel(ArtistRepository artists, IMapper mapper, AuthService authService)
        {
            _artists = artists;
            _mapper = mapper;
            _authService = authService;
        }
        [BindProperty]
        public ArtistDto Artist { get; set; } = null!;
        [TempData]
        public string? Message { get; set; }
        public IActionResult OnPost(Guid guid)
        {
            if (!ModelState.IsValid) { return Page(); }
            var artist = _artists.FindByGuid(guid);
            if (artist is null) {
                Message = "The artist doesn't exist.";
                return RedirectToPage("/Artists/Index");
            }
            _mapper.Map(Artist, artist);
            var (success, message) = _artists.Update(artist);
            if (!success)
            {
                ModelState.AddModelError("", message);
                return Page();
            }
            return RedirectToPage("/Artists/Index");
        }
        public IActionResult OnGet(Guid guid)
        {
            var artist = _artists.Set
                .Include(ar => ar.Manager)
                .Include(ar => ar.Albums)
                .Include(ar => ar.Songs)
                .FirstOrDefault(ar => ar.Guid == guid);
            if (artist is null) { return RedirectToPage("/Artists/Index"); }
            var username = _authService.Username;
            if(!_authService.HasRole("Admin") && username != artist.Manager.Username)
            {
                return new ForbidResult();
            }
            Artist = _mapper.Map<ArtistDto>(artist);
            return Page();
        }
    }
}

MusicCloud.Webapp/Pages/Artists/Index.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MusicCloud.Webapp.Pages.Artists
{
    public class IndexModel : PageModel
    {
        private readonly ArtistRepository _artists;
        private readonly UserRepository _users;
        private readonly IMapper _mapper;
        private readonly AuthService _authService;
        public IReadOnlyList<ArtistRepository.ArtistWithAlbumAndSongCount> Artists { get; private set; } = new List<ArtistRepository.ArtistWithAlbumAndSongCount>();

        public IndexModel(ArtistRepository artists, UserRepository users, IMapper mapper, AuthService authService)
        {
            _artists = artists;
            _users = users;
            _mapper = mapper;
            _authService = authService;
        }
        [BindProperty]
        public ArtistDto NewArtist { get; set; } = default!;
        public IEnumerable<SelectListItem> ManagerSelectList =>
            _users.Set.Where(u => u.Usertype == Application.Model.Usertype.Manager)
            .OrderBy(u => u.Username).Select(u => new SelectListItem(u.Username, u.Guid.ToString()));
        [TempData]
        public string? Message { get; set; }
        public IActionResult OnPostNewArtist(Guid guid)
        {
            if(!_authService.IsAdmin) {
                Message = "You are not authorized to add an Artist";
                return Page(); 
            }
            if (!ModelState.IsValid) { return Page(); }
            var artist = _mapper.Map<Artist>(NewArtist);
            if(NewArtist.ManagerGuid.HasValue)
            {
                var manager = _users.FindByGuid((Guid)NewArtist.ManagerGuid);
                if(manager.Usertype == Application.Model.Usertype.Admin)
                {
                    Message = "You can not add an Admin as a Manager";
                    return Page();
                }
                artist.Manager = manager;
            }
            var (success, message) = _artists.Insert(artist);
            if (!success)
            {
                ModelState.AddModelError("", message);
                return Page();
            }
            return RedirectToPage();
        }
        public IActionResult OnGet()
        {
            return Page();
        }

        public override void OnPageHandlerExecuting(PageHandlerExecutingContext context)
        {
            Artists = _artists.GetArtistsWithAlbumAndSongCount();
        }

        public bool CanEditArtist(Guid artistGuid) =>
            (_authService.IsAdmin ||
            Artists.FirstOrDefault(ar => ar.Guid == artistGuid)?.Manager?.Username == _authService.Username)
            && _authService.IsAuthenticated;

        public bool CanAddArtist() =>
            _authService.IsAdmin;
    }
}

MusicCloud.Webapp/Pages/Artists/Delete.cshtml
@page "{guid}"
@model MusicCloud.Webapp.Pages.Artists.DeleteArtistsModel
<h3>Artist löschen</h3>

<div class="border border-danger p-3">
    <p>Soll der Artist @Model.Artist.ArtistName gelöscht werden?</p>
    <form method="post">
        <button asp-page-handler="Delete" type="submit" class="btn btn-danger">Ja</button>
        <button asp-page-handler="Cancel" type="submit" class="btn btn-secondary">Nein</button>
    </form>
</div>

MusicCloud.Webapp/Pages/Artists/Details.cshtml
@page "{guid}"
@model MusicCloud.Webapp.Pages.Artists.ArtistDetailsModel
@section head
    {
    <style>
        .tableHead {
            background-color: lightgray;
        }
    </style>
}

<h3>Details to the artist <b>@Model.Artist.ArtistName</b></h3><br />

<h5>
    First Name: <b>@Model.Artist.FirstName</b><br />
    Last Name: <b>@Model.Artist.LastName</b><br />
    Birth Date: <b>@Model.Artist.Birthday</b><br />
    Total amount of albums: <b>@Model.Artist.Albums.Count</b><br />
    Total amount of songs: <b>@Model.Artist.Songs.Count</b>
</h5><br />

<h4>List of all albums</h4>
<table class="table table-sm">
    <thead class="tableHead">
        <tr>
            <th>Title</th>
            <th>Release date</th>
            <th>Number of songs</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var a in Model.Artist.Albums.OrderBy(a => a.ReleaseDate))
        {
            <tr>
                <td>@a.Title</td>
                <td>@a.ReleaseDate.ToString("dd.MM.yyyy")</td>
                <td>@a.Songs.Count</td>
                <td>
                    <a asp-page="/Albums/Details" asp-route-guid="@a.Guid">Details</a>
                    @if(Model.CanEditAlbum(a.Guid)) {
                        <a asp-page="/Albums/Edit" asp-route-guid="@a.Guid">Edit</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

MusicCloud.Webapp/Pages/Artists/Edit.cshtml
@page "{guid}"
@model MusicCloud.Webapp.Pages.Artists.EditArtistModel

<form method="post">
    <input type="hidden" asp-for="Artist.Guid"/>
    <table>
        <tr>
            <td><label asp-for="Artist.ArtistName">Artist Name</label></td>
            <td><input asp-for="Artist.ArtistName" /></td>
            <td colespan="2"><span class="text-danger" asp-validation-for="Artist.ArtistName"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Artist.FirstName">First Name</label></td>
            <td><input asp-for="Artist.FirstName" /></td>
            <td colespan="2"><span class="text-danger" asp-validation-for="Artist.FirstName"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Artist.LastName">Last Name</label></td>
            <td><input asp-for="Artist.LastName" /></td>
            <td colespan="2"><span class="text-danger" asp-validation-for="Artist.LastName"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Artist.Birthday">Birthday</label></td>
            <td><input asp-for="Artist.Birthday" type="date" value="@Model.Artist.Birthday.ToString("yyyy-MM-dd")"/></td>
            <td colespan="2"><span class="text-danger" asp-validation-for="Artist.Birthday"ö></span></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center"><button type="submit">Send</button></td>
        </tr>
    </table>
</form>

MusicCloud.Webapp/Pages/Artists/Index.cshtml
@page
@model MusicCloud.Webapp.Pages.Artists.IndexModel
@section head
{
    <style>
        .tableHead {
            background-color:lightgray;
        }
    </style>
}

@if(!string.IsNullOrEmpty(Model.Message))
{
    <div class="border border-danger p-3 border-3">
        <p class="mb-0">@Model.Message</p>
    </div>
}

@if(Model.CanAddArtist()) {
<form method="post" asp-page-handler="NewArtist">
    <div class="row">
        <div class="col-6">
            <label asp-for="NewArtist.ArtistName">Artist Name</label>
            <input class="form-control" asp-for="NewArtist.ArtistName" />
            <small>
                <span class="text-danger" asp-validation-for="NewArtist.ArtistName"></span>
            </small>
        </div>
        <div class="col-6">
            <label asp-for="NewArtist.FirstName">First Name</label>
                <input class="form-control" asp-for="NewArtist.FirstName" />
                <small>
                    <span class="text-danger" asp-validation-for="NewArtist.FirstName"></span>
                </small>
        </div>
        <div class="col-6">
            <label asp-for="NewArtist.LastName">Last Name</label>
                <input class="form-control" asp-for="NewArtist.LastName" />
                <small>
                    <span class="text-danger" asp-validation-for="NewArtist.LastName"></span>
                </small>
        </div>
        <div class="col-6">
            <label asp-for="NewArtist.Birthday">Birthday</label>
            <input class="form-control" asp-for="NewArtist.Birthday" type="date" value="@DateTime.Now.AddYears(-18).ToString("yyyy-MM-dd")" max="@DateTime.Now.AddYears(-18).ToString("yyyy-MM-dd")" />
                <small>
                    <span class="text-danger" asp-validation-for="NewArtist.Birthday"></span>
                </small>
        </div>
        <div class="col-6">
            <label asp-for="NewArtist.ManagerGuid">Manager</label>
                <select class="form-control" asp-items="@Model.ManagerSelectList"
                        asp-for="NewArtist.ManagerGuid">
                        <option value="" selected>No Manager</option>
                </select>
            <small>
                    <span class="text-danger" asp-validation-for="NewArtist.ManagerGuid"></span>
            </small>
        </div>
    </div>
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <button class="mt-2 btn btn-primary">Speichern</button>
</form>
}

<h3>Artists in the database</h3>
<p>Found @Model.Artists.Count Artists at @DateTime.Now.ToString("HH:mm")</p>

<table class="table table-sm">
    <thead>
        <tr class="tableHead">
            <th>Artist Name</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Birthday</th>
            <th>Albums</th>
            <th>Songs</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var ar in Model.Artists)
        {
            <tr>
                <td>@ar.ArtistName</td>
                <td>@ar.FirstName</td>
                <td>@ar.LastName</td>
                <td>@ar.Birthday.ToString("dd.MM.yyyy")</td>
                <td>@ar.AlbumsCount</td>
                <td>@ar.SongsCount</td>
                <td>
                    <a asp-page="/Artists/Details" asp-route-guid="@ar.Guid">Details</a>
                    @if(Model.CanEditArtist(ar.Guid)) {
                        <a asp-page="/Artists/Edit" asp-route-guid="@ar.Guid">Edit</a>
                        <a asp-page="/Artists/Delete" asp-route-guid="@ar.Guid">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>