MusicCloud.Webapp/Pages/Albums/Details.cshtml.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;
using System;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;

namespace MusicCloud.Webapp.Pages.Albums
{
  
    public class AlbumDetailsModel : PageModel
    {
        private readonly AlbumRepository _albums;
        private readonly SongRepository _songs;
        private readonly IMapper _mapper;
        private readonly AuthService _authService;
        public AlbumDetailsModel(AlbumRepository albums, SongRepository songs, IMapper mapper, AuthService authService)
        {
            _albums = albums;
            _songs = songs;
            _mapper = mapper;
            _authService = authService;
        }

        [FromRoute]
        public Guid Guid { get; set; }
        public Album Album { get; private set; } = default!;
        [BindProperty]
        public Dictionary<Guid, SongDto> EditSongs { get; set; } = new();

        public IActionResult OnPostEditSong(Guid guid, Guid songGuid, Dictionary<Guid, SongDto> editSongs)
        {
            if (!ModelState.IsValid) { return Page(); }
            var song = _songs.FindByGuid(songGuid);
            if (song is null) { return RedirectToPage(); }

            _mapper.Map(editSongs[songGuid], song);
            var (success, message) = _songs.Update(song);
            if (!success)
            {
                ModelState.AddModelError("", message);
                return Page();
            }
            return RedirectToPage();
        }
        public IActionResult OnGet(Guid guid)
        {
            return Page();
        }

        public override void OnPageHandlerExecuting(PageHandlerExecutingContext context)
        {
            var album = _albums.Set
                .Include(a => a.Songs)
                .ThenInclude(s => s.Genre)
                .Include(a => a.Artist)
                .ThenInclude(ar => ar.Manager)
                .FirstOrDefault(a => a.Guid == Guid);
            if (album is null)
            {
                context.Result = RedirectToPage("/Artists/Index");
                return;
            }
            Album = album;
            EditSongs =
                _songs.Set.Where(s => s.Album.Guid == Guid)
                .ProjectTo<SongDto>(_mapper.ConfigurationProvider)
                .ToDictionary(s => s.Guid, s => s);
        }

        public bool CanEditAlbum(Guid albumGuid) =>
        _authService.IsAdmin ||
            _albums.Set
            .FirstOrDefault(a => a.Guid == albumGuid)?
            .Artist?.Manager?.Username == _authService.Username;
    }
}

MusicCloud.Webapp/Pages/Albums/Edit.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;

namespace MusicCloud.Webapp.Pages.Albums
{
    [Authorize]
    public class EditAlbumModel : PageModel
    {
        private readonly AlbumRepository _albums;
        private readonly ArtistRepository _artists;
        private readonly IMapper _mapper;
        private readonly AuthService _authService;
        public EditAlbumModel(AlbumRepository albums, ArtistRepository artists, IMapper mapper, AuthService authService)
        {
            _albums = albums;
            _artists = artists;
            _mapper = mapper;
            _authService = authService;
        }
        [BindProperty]
        public AlbumDto Album { get; set; } = null!;
        [TempData]
        public string? Message { get; set; }
        public IEnumerable<SelectListItem> ArtistSelectList =>
            _artists.Set.OrderBy(ar => ar.ArtistName).Select(ar => new SelectListItem(ar.ArtistName, ar.Guid.ToString()));
        public IActionResult OnPost(Guid guid)
        {
            if (!ModelState.IsValid) { return Page(); }
            var album = _albums.Set
                .Include(a => a.Artist)
                .Include(a => a.Songs)
                .FirstOrDefault(a => a.Guid == guid);
            if (album is null) {
                Message = "The album doesn't exist.";
                return RedirectToPage("/Artists/Index");
            }
            
            var artist = _artists.FindByGuid(Album.ArtistGuid);
            if (artist is null) {
                Message = "The artist doesn't exist.";
                return RedirectToPage("/Artists/Index");
            }
            album.Artist = artist;

            album.Songs.ToList().ForEach(a => a.Artist = artist);
            _mapper.Map(Album, album);
            var (success, message) = _albums.Update(album);
            if(!success) { ModelState.AddModelError("", message); }
            return RedirectToPage("/Artists/Index");
        }
        public IActionResult OnGet(Guid guid)
        {
            var albums = _albums.Set
                .Include(a => a.Artist)
                .ThenInclude(ar => ar.Manager)
                .FirstOrDefault(a => a.Guid == guid);
            if (albums is null) { return RedirectToPage("/Artists/Index"); }
            if(!_authService.IsAdmin && _authService.Username != albums.Artist.Manager.Username)
            {
                return new ForbidResult();
            }
            Album = _mapper.Map<AlbumDto>(albums);
            return Page();
        }

        public bool CanEditArtist()
        {
            return _authService.IsAdmin;
        }
    }

}

MusicCloud.Webapp/Pages/Artists/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;
using System;
using System.Linq;

namespace MusicCloud.Webapp.Pages.Artists
{
    public class ArtistDetailsModel : PageModel
    {
        private readonly ArtistRepository _artists;
        private readonly AlbumRepository _albums;
        private readonly AuthService _authService;
        public ArtistDetailsModel(ArtistRepository artists, AlbumRepository albums, AuthService authService)
        {
            _artists = artists;
            _albums = albums;
            _authService = authService;
        }
        [BindProperty]
        public Artist Artist { get; set; } = default!;
        public IActionResult OnGet(Guid guid)
        {
            var artist = _artists.Set
                .Include(ar => ar.Albums)
                .Include(ar => ar.Songs)
                .Include(ar => ar.Manager)
                .FirstOrDefault(a => a.Guid == guid);

            if (artist == null)
            {
                return RedirectToPage("/Artists/Index");
            }
            Artist = artist;
            return Page();
        }
        public bool CanEditAlbum(Guid albumGuid) =>
        _authService.IsAdmin ||
            _albums.Set.FirstOrDefault(a => a.Guid == albumGuid)?.Artist.Manager?.Username == _authService.Username;
    }
}

MusicCloud.Webapp/Pages/Artists/Edit.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MusicCloud.Application.infrastructure;
using MusicCloud.Application.Infrastructure.Repositories;
using MusicCloud.Application.models;
using MusicCloud.Webapp.Dto;
using MusicCloud.Webapp.Services;

namespace MusicCloud.Webapp.Pages.Artists
{
    [Authorize]
    public class EditArtistModel : PageModel
    {
        private readonly ArtistRepository _artists;
        private readonly IMapper _mapper;
        private readonly AuthService _authService;
        public EditArtistModel(ArtistRepository artists, IMapper mapper, AuthService authService)
        {
            _artists = artists;
            _mapper = mapper;
            _authService = authService;
        }
        [BindProperty]
        public ArtistDto Artist { get; set; } = null!;
        [TempData]
        public string? Message { get; set; }
        public IActionResult OnPost(Guid guid)
        {
            if (!ModelState.IsValid) { return Page(); }
            var artist = _artists.FindByGuid(guid);
            if (artist is null) {
                Message = "The artist doesn't exist.";
                return RedirectToPage("/Artists/Index");
            }
            _mapper.Map(Artist, artist);
            var (success, message) = _artists.Update(artist);
            if (!success)
            {
                ModelState.AddModelError("", message);
                return Page();
            }
            return RedirectToPage("/Artists/Index");
        }
        public IActionResult OnGet(Guid guid)
        {
            var artist = _artists.Set
                .Include(ar => ar.Manager)
                .Include(ar => ar.Albums)
                .Include(ar => ar.Songs)
                .FirstOrDefault(ar => ar.Guid == guid);
            if (artist is null) { return RedirectToPage("/Artists/Index"); }
            var username = _authService.Username;
            if(!_authService.HasRole("Admin") && username != artist.Manager.Username)
            {
                return new ForbidResult();
            }
            Artist = _mapper.Map<ArtistDto>(artist);
            return Page();
        }
    }
}

MusicCloud.Webapp/Pages/Albums/Details.cshtml
@page "{guid}"
@model MusicCloud.Webapp.Pages.Albums.AlbumDetailsModel
@section head
    {
    <style>
        .tableHead {
            background-color: lightgray;
        }
    </style>
}

<h3>Details to the album <b>@Model.Album.Title</b></h3>
<br />

<h5>
    Title: <b>@Model.Album.Title</b><br />
    Artist: <b><a asp-page="/Artists/Details" asp-route-guid="@Model.Album.Artist.Guid">@Model.Album.Artist.ArtistName</a></b><br />
    Release Date: <b>@Model.Album.ReleaseDate</b><br />
    Total amount of songs: <b>@Model.Album.Songs.Count</b>
</h5><br />

<h4>List of all songs</h4>
<form method="post" asp-page-handler="EditSong">
    <table class="table table-sm">
        <thead class="tableHead">
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Length</th>
                <th>Release Date</th>
                @if(Model.CanEditAlbum(Model.Album.Guid)) {
                    <th>Action</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach(var s in Model.Album.Songs)
            {
                if(Model.CanEditAlbum(Model.Album.Guid)) {
                    <tr>
                        <td>
                            <input type="hidden" asp-for="EditSongs[s.Guid].Guid" />
                            <input type="hidden" asp-for="EditSongs[s.Guid].AlbumGuid" />
                            <input asp-for="EditSongs[s.Guid].Title" type="text" class="form-control" placeholder="Title" value="@s.Title" />
                            <small>
                                <span class="text-danger" asp-validation-for="EditSongs[s.Guid].Title"></span>
                            </small>
                        </td>
                        <td>@s.Genre.Name</td>
                        <td>
                            @{
                                int minutes = (int)Math.Floor((double)s.Length / 60);
                                int seconds = s.Length % 60;
                                <input asp-for="EditSongs[s.Guid].Length" type="text" class="form-control" placeholder="Length (mm:ss)" pattern="\d{1,2}:\d{2}" value="@String.Format("{0:D2}:{1:D2}", minutes, seconds)" />
                                <small>
                                    <span class="text-danger" asp-validation-for="EditSongs[s.Guid].Length"></span>
                                </small>
                            }
                        </td>
                        <td>
                            <input asp-for="EditSongs[s.Guid].ReleaseDate" type="date" value="@s.ReleaseDate.ToString("yyyy-MM-dd")" />
                            <small>
                                <span class="text-danger" asp-validation-for="EditSongs[s.Guid].ReleaseDate"></span>
                            </small>
                        </td>
                        <td>
                            <button class="btn btn-primary"
                                type="submit" 
                                asp-page-handler="EditSong"
                                asp-route-songGuid="@s.Guid">
                                Save
                            </button>
                        </td>
                    </tr>
                } else
                {
                    <tr>
                        <td>@s.Title</td>
                        <td>@s.Genre.Name</td>
                        <td>
                            @{
                                int minutes = (int)Math.Floor((double)s.Length / 60);
                                int seconds = s.Length % 60;
                                @String.Format("{0:D2}:{1:D2}", minutes, seconds)
                            }
                        </td>
                        <td>@s.ReleaseDate.ToString("dd.MM.yyyy")</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</form>

MusicCloud.Webapp/Pages/Albums/Edit.cshtml
@page "{guid}"
@model MusicCloud.Webapp.Pages.Albums.EditAlbumModel

<form method="post">
    <input type="hidden" asp-for="Album.Guid"/>
    <table>
        <tr>
            <td><label asp-for="Album.ArtistGuid">Artist</label></td>
            <td>
                <select 
                    asp-items="@Model.ArtistSelectList"
                    asp-for="Album.ArtistGuid">
                </select>
            </td>
            <td colespan="2"><span class="text-danger" asp-validation-for="Album.ArtistGuid"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Album.Title">Title</label></td>
            <td><input asp-for="Album.Title" /></td>
            <td colespan="2"><span class="text-danger" asp-validation-for="Album.Title"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Album.ReleaseDate">Release Date</label></td>
            <td><input asp-for="Album.ReleaseDate" type="date" value="@Model.Album.ReleaseDate.ToString("yyyy-MM-dd")" /></td>
            <td colespan="2"><span class="text-danger" asp-validation-for="Album.ReleaseDate"></span></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center"><button type="submit">Send</button></td>
        </tr>
    </table>
</form>